# Google App Store EDA

# Columns Break Down
1. App: Name of app and uses.
2. Category: For which purpose this app is design (eg: art,economics,entertainment).
3. Rating: The pupolarity of app.
4. Reviews: The people reviews for app.
5. Size: The size of app.
6. Install: How many people install it.
7. Type: Is it free or not.
8. Price: Price of app.
9. Content Rating: Which type of people can use it(eg:adult,kids etc).
10. Genres: Description of app or purpose.
11. Last_upadate: The date of last update of the app.
12. Current_ver: The current version of the app.
13. Andriod_ver: The cureent version of the Andriod_ver.

In [19]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
# import dataset
df = pd.read_csv('./data/googleplaystore.csv')
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Life Made WI-Fi Touchscreen Photo Frame,GAME,1.9,3.0M,"1,000+",0,Free,0,Everyone,Casual,"February 11, 2018",4.0 and up,4.0 and up
1,Viber Messenger,COMMUNICATION,4.3,11334799,Varies with device,"500,000,000+",Free,0,Everyone,Communication,"July 18, 2018",Varies with device,Varies with device
2,imo free video calls and chat,COMMUNICATION,4.3,4785892,11M,"500,000,000+",Free,0,Everyone,Communication,"June 8, 2018",9.8.000000010501,4.0 and up
3,Google Duo - High Quality Video Calls,COMMUNICATION,4.6,2083237,Varies with device,"500,000,000+",Free,0,Everyone,Communication,"July 31, 2018",37.1.206017801.DR37_RC14,4.4 and up
4,UC Browser - Fast Download Private & Secure,COMMUNICATION,4.5,17712922,40M,"500,000,000+",Free,0,Teen,Communication,"August 2, 2018",12.8.5.1121,4.0 and up

In [21]:
# run automatic EDA using ydata-profiling library
# import ydata_profiling as yd
# profile = yd.ProfileReport(df)
# profile.to_file(output_file="./outputs/07_ydata_googleplaystore.html")

In [22]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [23]:
# check the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10841 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10839 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [24]:
# lets have a look at the data
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Life Made WI-Fi Touchscreen Photo Frame,GAME,1.9,3.0M,"1,000+",0,Free,0,Everyone,Casual,"February 11, 2018",4.0 and up,4.0 and up
1,Viber Messenger,COMMUNICATION,4.3,11334799,Varies with device,"500,000,000+",Free,0,Everyone,Communication,"July 18, 2018",Varies with device,Varies with device
2,imo free video calls and chat,COMMUNICATION,4.3,4785892,11M,"500,000,000+",Free,0,Everyone,Communication,"June 8, 2018",9.8.000000010501,4.0 and up
3,Google Duo - High Quality Video Calls,COMMUNICATION,4.6,2083237,Varies with device,"500,000,000+",Free,0,Everyone,Communication,"July 31, 2018",37.1.206017801.DR37_RC14,4.4 and up
4,UC Browser - Fast Download Private & Secure,COMMUNICATION,4.5,17712922,40M,"500,000,000+",Free,0,Teen,Communication,"August 2, 2018",12.8.5.1121,4.0 and up

In [25]:
# take sample from the big dataset
df.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1614,DV 2019 - EDV Photo & Form,BOOKS_AND_REFERENCE,3.9,314,2.6M,"50,000+",Free,0,Everyone,Books & Reference,"October 24, 2016",6.0.0,4.0.3 and up
7473,Travis CU,FINANCE,2.0,207,2.9M,"10,000+",Free,0,Everyone,Finance,"February 16, 2018",1.0.0.9,4.4 and up
4909,Denis Brogniart - AH 2 !,FAMILY,NaN,4,14M,100+,Free,0,Everyone,Entertainment,"October 28, 2017",1.0,2.1 and up
7218,bd's Mongolian Grill,LIFESTYLE,4.2,120,14M,"10,000+",Free,0,Everyone,Lifestyle,"February 23, 2018",1.5.1,4.1 and up
3867,I will return his eggs,LIBRARIES_AND_DEMO,NaN,91,18M,"100,000+",Free,0,Everyone,Libraries & Demo,"November 16, 2017",6.0,2.3 and up
4016,Development of the child up to a year,PARENTING,4.6,1413,14M,"100,000+",Free,0,Mature 17+,Parenting,"July 20, 2018",2.9.9,4.1 and up
5478,HD Wallpaper - Toyota FJ Cruiser,TOOLS,NaN,2,6.2M,100+,Free,0,Everyone,Tools,"November 10, 2017",1.0,4.0 and up
10424,CX-10DS,FAMILY,3.4,12,11M,"1,000+",Free,0,Everyone,Casual,"September 15, 2017",1.5_6,4.0 and up
1311,Brilliant Distinctions®,MEDICAL,2.8,78,72M,"50,000+",Free,0,Everyone,Medical,"June 27, 2018",2.2.12,4.4 and up
1748,A-J Media Vault,BOOKS_AND_REFERENCE,NaN,1,24M,50+,Free,0,Everyone,Books & Reference,"January 4, 2017",5.62.1,4.0.3 and up

In [26]:
#
df.describe()

            Rating
count  9367.000000
mean      4.191513
std       0.515735
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max       5.000000

# write down all the numeric variables and make them numeric

1. size
2. insall 
3. price

In [28]:
# to do tha lets have a look on unique values
df['Size'].value_counts()

Size
Varies with device    1695
11M                    198
12M                    196
14M                    194
13M                    191
                      ...
173k                     1
597k                     1
809k                     1
411k                     1
885k                     1
Name: count, Length: 462, dtype: int64

In [29]:
df['Size'].isnull().sum()

np.int64(0)

In [30]:
df['Installs'].value_counts()

Installs
1,000,000+        1579
10,000,000+       1252
100,000+          1169
10,000+           1054
1,000+             907
5,000,000+         752
100+               719
500,000+           539
50,000+            479
5,000+             477
100,000,000+       409
10+                386
500+               330
50,000,000+        289
50+                205
5+                  82
500,000,000+        72
1+                  67
1,000,000,000+      58
0+                  14
0                    2
Name: count, dtype: int64

In [ ]:
# do it as numeric column or group that into categories

In [31]:
df['Price'].value_counts()

Price
0          10041
$0.99        148
$2.99        129
$1.99         73
$4.99         72
           ...
$3.90          1
$2.95          1
$1.97          1
$1.20          1
$394.99        1
Name: count, Length: 92, dtype: int64

In [32]:
df['Price'].isnull().sum()

np.int64(0)

In [ ]:
# remove $ sign from all columns using pandas.

In [33]:
df['Type'].value_counts()

Type
Free    10040
Paid      800
Name: count, dtype: int64